
version: '3.3'
services:
  postgresql:
    image: postgres:11.7-alpine
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_DB=testwebinterpret
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

