"""Creating production and seller model

Revision ID: 05640dd7788c
Revises: 94989eb07553
Create Date: 2022-03-15 23:36:05.406355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05640dd7788c'
down_revision = '94989eb07553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('seller', sa.Column('name', sa.String(), nullable=True))
    op.add_column('seller', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'created_at')
    op.drop_column('seller', 'name')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
