"""Creating production and seller model

Revision ID: 18e363702411
Revises: 61c04e861c7c
Create Date: 2022-03-16 03:03:23.396392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e363702411'
down_revision = '61c04e861c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
