"""Creating production and seller model

Revision ID: 61c04e861c7c
Revises: 631715119f2b
Create Date: 2022-03-16 02:58:02.627960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c04e861c7c'
down_revision = '631715119f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
