"""Creating production and seller model

Revision ID: 631715119f2b
Revises: 05640dd7788c
Create Date: 2022-03-16 02:23:28.596075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631715119f2b'
down_revision = '05640dd7788c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
