"""Creating production and seller model

Revision ID: 94989eb07553
Revises: 7cd2cacecbf3
Create Date: 2022-03-15 22:56:06.270057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94989eb07553'
down_revision = '7cd2cacecbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('country_code', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('price', sa.FLOAT(precision=11), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('products')
    op.drop_table('seller')
    # ### end Alembic commands ###
